### PR TITLE
Run CI on macOS (in addition to Linux and Windows)

### PR DESCRIPTION
**Pull request by DilumAluthge**
VectorizationBase.jl runs CI on macOS, since those machines are older and often don't have AVX2.

Would it make sense to do the same thing for LoopVectorization.jl?

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Also, there are some test failures on other platforms.

**Comment by chriselrod** [comment]
One of the failures was because of a missing Julia version check.
Another one I can't reproduce on AVX512 machines:
```julia
julia> include("/home/chriselrod/.julia/dev/LoopVectorization/test/tullio.jl")
Test Summary: | Pass  Total
Tullio Tests  |    6      6
Test.DefaultTestSet("Tullio Tests", Any[], 6, false, false)
```
versus CI
```julia
Tullio Tests: Error During Test at /home/runner/work/LoopVectorization.jl/LoopVectorization.jl/test/tullio.jl:4
  Got exception outside of a @test
  MethodError: no method matching _vstore!(::VectorizationBase.OffsetPrecalc{Float64,5,1,0,(1, 2, 3, 4, 5),Tuple{Static.StaticInt{8},Int64,Int64,Int64,Int64},NTuple{5,Static.StaticInt{0}},VectorizationBase.StridedPointer{Float64,5,1,0,(1, 2, 3, 4, 5),Tuple{Static.StaticInt{8},Int64,Int64,Int64,Int64},NTuple{5,Static.StaticInt{0}}},Tuple{Nothing,Tuple{Int64,Int64},Tuple{Int64,Int64},Tuple{Int64,Int64},Tuple{Int64,Int64}}}, ::VectorizationBase.VecUnroll{2,1,Float64,Float64}, ::VectorizationBase.Unroll{2,1,3,1,4,0x0000000000000007,1,NTuple{5,Static.StaticInt{0}}}, ::VectorizationBase.EVLMask{4,UInt8}, ::Static.False, ::Static.True, ::Static.False, ::Static.StaticInt{32})
  Closest candidates are:
    _vstore!(::VectorizationBase.AbstractStridedPointer{T,N,C,B,R,X,O} where O<:Tuple{Vararg{Any,N}} where X<:Tuple{Vararg{Any,N}} where R where B where C where N, ::Any, !Matched::Tuple{I}, ::Union{Bool, VectorizationBase.AbstractMask}, ::A, ::S, ::NT, ::Static.StaticInt{RS}) where {T, I, A<:Static.StaticBool, S<:Static.StaticBool, NT<:Static.StaticBool, RS} at /home/runner/.julia/packages/VectorizationBase/rJ58l/src/strided_pointers/stridedpointers.jl:199
    _vstore!(::VectorizationBase.AbstractStridedPointer{T,N,C,B,R,X,O} where O<:Tuple{Vararg{Any,N}} where X<:Tuple{Vararg{Any,N}} where R where B where C, ::Any, !Matched::Tuple{Vararg{Any,N}}, ::Union{Bool, VectorizationBase.AbstractMask}, ::A, ::S, ::NT, ::Static.StaticInt{RS}) where {T, N, A<:Static.StaticBool, S<:Static.StaticBool, NT<:Static.StaticBool, RS} at /home/runner/.julia/packages/VectorizationBase/rJ58l/src/strided_pointers/stridedpointers.jl:187
    _vstore!(::VectorizationBase.AbstractStridedPointer, !Matched::V, ::VectorizationBase.Unroll{AU,F,N,AV,W,M,X,I} where I where X where M, ::Union{Bool, VectorizationBase.AbstractMask, VectorizationBase.VecUnroll}, ::A, ::S, ::NT, ::Static.StaticInt{RS}) where {A<:Static.StaticBool, S<:Static.StaticBool, NT<:Static.StaticBool, RS, W, T, V<:VectorizationBase.AbstractSIMDVector{W,T}, AU, F, N, AV} at /home/runner/.julia/packages/VectorizationBase/rJ58l/src/vecunroll/memory.jl:753
```
I'll define the missing method in VectorizationBase.

But the macs seem to have extra failures that I'll have to look at.

**Comment by chriselrod** [comment]
Ha ha, sure enough, all tests passed on AVX512+Julia nightly.

**Comment by chriselrod** [comment]
Mind requiring VectorizationBase 0.19.17, and editing `test/shuffleloadstorrs.jl` to only run the `issue209` test when
```julia
if VERSION ≥ v"1.6.0-rc1"
   M = 100
    G = 50
    ...
```
?

**Comment by DilumAluthge** [comment]
> Mind merging in master once tests finally pass on master?

Definitely! Ping me once tests are passing on master?

**Comment by DilumAluthge** [comment]
@chriselrod I have rebased this PR on the latest master.

**Comment by chriselrod** [comment]
Yikes, that is a lot of failures. I'll take a look at them later.

**Comment by DilumAluthge** [comment]
I just rebased on the latest master - not as many failures now.

**Comment by DilumAluthge** [comment]
Huh, now there is a single Windows failure.

**Comment by chriselrod** [comment]
I'm not sure what's causing the Windows 1.6 failure. It seemed like it may be crashing on `using Zygote`.

**Comment by DilumAluthge** [comment]
Can you see the log now?

**Comment by chriselrod** [comment]
Yes.
```julia
 171.737179 seconds (37.54 M allocations: 6.632 GiB, 0.60% gc time, 81.03% compilation time)
Internal error: encountered unexpected error in runtime:
ReadOnlyMemoryError()
reset_page at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1155 [inlined]
add_page at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1187
jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1240 [inlined]
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:285 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3283
_new_array_ at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:122
_new_array at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:188 [inlined]
jl_alloc_array_1d at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:459
```
Same as:
https://github.com/JuliaSIMD/LoopVectorization.jl/pull/223#issuecomment-807915166

The crash seems to happen during `using Zygote`.
FWIW, Zygote only seems to be tested on Ubuntu, and these crashes are Windows only.

I don't have a Windows machine to test, but I can't help but thing someone would've noticed and filed an issue if `using Zygote` was broken on Windows on Julia 1.6.

**Comment by DilumAluthge** [comment]
In the LV test suite, should we skip all the Zygote tests (and also skip the `using Zygote`) if `Sys.iswindows()` is true?

**Comment by chriselrod** [comment]
It only seems to be a problem with Julia 1.6.
But I think that'd be a good idea.
There's a chance that the problem is in shuffleloadstores, but that the crash doesn't happen until later. So it'd be good to confirm tests pass without the `using Zygote` and that the problem isn't with LV, in which case one of us could file an issue with Zygote.

**Comment by chriselrod** [comment]
Okay, now the Windows failures are because:
```julia
   MethodError: no method matching reinterpret(::typeof(reshape), ::Type{Float64}, ::Array{Complex{Float64},1})
  Closest candidates are:
    reinterpret(!Matched::Type{T}, ::Any) where T at essentials.jl:414
```
It isn't supposed to be evaluating these tests in Julia 1.5. Obviously, it wasn't on Ubuntu or Mac.

**Comment by chriselrod** [comment]
It says the Windows test was cancelled? I can't view the details.

**Comment by DilumAluthge** [comment]
Can you fix the merge conflicts?

**Comment by chriselrod** [comment]
The Windows 1.6 problem is unrelated. Assuming all tests but Windows pass, I'll merge.

Assuming Windows 1.6 fails, I'll create an issue.

**Pull request merged**
