### PR TITLE
Update to ArrayInterface v4

### PR DESCRIPTION
**Pull request by Tokazama**
I still need to figure out versioning for tests but I think this is all that needs to change.

### CODE REVIEW

**Comment by chriselrod** [comment]
ArrayInterface 4 requires Julia >= 1.6. So Julia 1.5 can be updated to 1.6, so we test on 1.6, the latest release ("1" => currently 1.7) and nightly.

But the Julia 1 and nightly failures look real.

**Comment by chriselrod** [comment]
Also:
```julia
   MethodError: no method matching eachop(::typeof(ArrayInterface._known_size), ::Tuple{}, ::Type{Tuple{}})
  Closest candidates are:
    eachop(::F, ::Tuple{I}, ::Any...) where {F, I, K} at ~/.julia/packages/Static/ARZ1c/src/tuples.jl:40
    eachop(::F, ::Tuple{I1, I2, Vararg}, ::Any...) where {F, I1, I2, K} at ~/.julia/packages/Static/ARZ1c/src/tuples.jl:37
```
https://github.com/JuliaSIMD/LoopVectorization.jl/runs/5186578238?check_suite_focus=true

**Comment by Tokazama** [comment]
> Also:
> 
> ```julia
>   MethodError: no method matching eachop(::typeof(ArrayInterface._known_size), ::Tuple{}, ::Type{Tuple{}})
>   Closest candidates are:
>     eachop(::F, ::Tuple{I}, ::Any...) where {F, I, K} at ~/.julia/packages/Static/ARZ1c/src/tuples.jl:40
>     eachop(::F, ::Tuple{I1, I2, Vararg}, ::Any...) where {F, I1, I2, K} at ~/.julia/packages/Static/ARZ1c/src/tuples.jl:37
>   Stacktrace:
>     [1] _maybe_known_size(#unused#::Base.HasShape{0}, #unused#::Type{CartesianIndices{0, Tuple{}}})
>       @ ArrayInterface ~/.julia/packages/ArrayInterface/mJodK/src/size.jl:112
>     [2] known_size(#unused#::Type{CartesianIndices{0, Tuple{}}})
>       @ ArrayInterface ~/.julia/packages/ArrayInterface/mJodK/src/size.jl:110
>     [3] _maybe_known_length(#unused#::Base.HasShape{0}, #unused#::Type{CartesianIndices{0, Tuple{}}})
>       @ ArrayInterface ~/.julia/packages/ArrayInterface/mJodK/src/ArrayInterface.jl:96
>     [4] known_length(#unused#::Type{CartesianIndices{0, Tuple{}}})
>       @ ArrayInterface ~/.julia/packages/ArrayInterface/mJodK/src/ArrayInterface.jl:95
>     [5] known_length(x::CartesianIndices{0, Tuple{}})
>       @ ArrayInterface ~/.julia/packages/ArrayInterface/mJodK/src/ArrayInterface.jl:89
>     [6] maybe_static(f::typeof(ArrayInterface.known_length), g::typeof(length), x::CartesianIndices{0, Tuple{}})
>       @ Static ~/.julia/packages/Static/ARZ1c/src/int.jl:121
>     [7] static_length(x::CartesianIndices{0, Tuple{}})
>       @ ArrayInterface ~/.julia/packages/ArrayInterface/mJodK/src/ArrayInterface.jl:38
> ```
> 
> https://github.com/JuliaSIMD/LoopVectorization.jl/runs/5186578238?check_suite_focus=true
> 
> Versus ArrayInterface 3:
> 
> ```julia
> julia> ArrayInterface.static_length(CartesianIndices(()))
> 1
> ```
> 
> This could of course be `static(1)`.

Looks like we need a special case for zero dimensions? I'll look into these other issues some more

**Comment by chriselrod** [comment]
> Looks like we need a special case for zero dimensions? 

They don't really need to return `static(1)`, but they come from code like
```julia
using LoopVectorization, Test
function smoothdim_kernel_tile_avx!(out, z, src::AbstractArray, kernel::AbstractVector, Rpre::CartesianIndices, axout_tile, Rpost::CartesianIndices)
    axkernel = axes(kernel, 1)
    zout = convert(eltype(out), z)
    for Ipost in Rpost
        @turbo for i in axout_tile
            for Ipre in Rpre
                tmp = zout
                # tmp = convert(eltype(out), z)    # failing to hoist this leads to an "UndefVarError: tmp not defined"
                for j in axkernel
                    tmp += oftype(z, src[Ipre, i+j, Ipost]) * kernel[j]
                end
                out[Ipre, i, Ipost] = tmp
            end
        end
    end
    out
end

# Mimic of ImageFiltering/ArrayFiltering's separable filters
σ = 3
ax = OffsetArray(-6:6, -6:6)
kernel = float(T)[exp(-i^2 / (2 * σ^2)) for i in ax]   # 1-d Gaussian kernel
kernel ./= sum(kernel)
srcax = 1+firstindex(ax):M+lastindex(ax)
Mpad = length(srcax)
src = OffsetArray(rand(T, Mpad, Mpad, Mpad, Mpad, Mpad), srcax, srcax, srcax, srcax, srcax)
dest1 = Array{float(T),5}(undef, M, M, M, M, M)
dest2 = similar(dest1)
for d = 1:ndims(src)
    Rpre = CartesianIndices(axes(dest1)[1:d-1])
    Rpost = CartesianIndices(axes(dest1)[d+1:end])
    smoothdim_kernel_tile!(dest1, float(zero(T)), src, kernel, Rpre, axes(dest1, d), Rpost) # version without `@turbo`
    smoothdim_kernel_tile_avx!(dest2, float(zero(T)), src, kernel, Rpre, axes(dest2, d), Rpost)
    @test dest1 ≈ dest2
    fill!(dest2, NaN)
    smoothdim_kernel_tile_avx_2!(dest2, float(zero(T)), src, kernel, Rpre, axes(dest2, d), Rpost)
    @test dest1 ≈ dest2
end
```
I.e., `Rpre` and `Rpost` both might be 0-dimensional here, and the code should be able to handle this.

**Comment by Tokazama** [comment]
The problem with zero dimensions has been fixed. It was a bug with `Static.eachop`. I'm still getting a single error for broadcast tests.

**Comment by Tokazama** [comment]
A little bit more on the problem with broadcasting. It's specifically with `*ˡ`.
If you drop the adjoint and just do `@tturbo @. D2 = A *ˡ b` then you still get `NaN`s, but `@tturbo @. (b .+ x')` works just fine.

**Pull request closed without merging**
