### PR TITLE
Use 16 bits to store an array reference index

### PR DESCRIPTION
**Pull request by johnbcoughlin**
This seems to work without causing any extra errors, hopefully CI bears it out.

### CODE REVIEW

**Comment by chriselrod** [comment]
Thanks. I guess you've confirmed this fixes your problem locally?

If it's not too much trouble, mind adding a test?

Also, please feel free to bump the patch version so I can issue a new release after merging.

**Comment by johnbcoughlin** [comment]
Done. The new test fails on master with the same error. Let me know if you'd like me to test a more general property now that the 8 bit limit is raised.

**Review by chriselrod — APPROVED** [review]
Thanks, looks great!

**Comment by chriselrod** [comment]
Failures are unrelated to this PR.

**Pull request merged**
