### PR TITLE
Use VecUnroll, add threading support

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
A few questions:
1. If I do `@avx for ... end` and I don't specify the value for `thread`, what is the default value that is used for `thread`?
2. Am I correct in saying that `@avxt for ... end` is exactly equivalent to doing `@avx thread=true for ... end`?
3. What happens if I do `@avxt thread=false for ... end`? Which value is used for `thread`? Similarly, what if I do `@avxt thread=3 for ... end`?

**Comment by chriselrod** [comment]
I should definitely add docs that answer those questions.

> * If I do `@avx for ... end` and I don't specify the value for `thread`, what is the default value that is used for `thread`?

LoopVectorization picks. I thinking the picking algorithm and ramp-up as a function of loop sizes needs work.
It probably errs on the side of too few threads right now.

> * Am I correct in saying that `@avxt for ... end` is exactly equivalent to doing `@avx thread=true for ... end`?

Yes.

> * What happens if I do `@avxt thread=false for ... end`? Which value is used for `thread`? Similarly, what if I do `@avxt thread=3 for ... end`?

`@avxt thread=false for ... end` is equivalent to `@avx thread=false for ... end`.
Later arguments overrule earlier ones, and `@avxt thread=false for ... end` -> `@avx thread=true thread=false for ... end`
So the second (`false`) wins.

Same story with `thread=3`. However, `thread=number` sets the number as the maximum amount of threads to use. LoopVectorization can (currently) still decide to use less.
I may change that, because it certainly makes testing what the fastest number of threads is less convenient.

**Comment by chriselrod** [comment]
fixes #132

Benchmark:
https://github.com/chriselrod/LoopVectorization.jl/issues/132#issuecomment-652575612

Performance, with the original code as from that comment:
```julia
julia> @show go(128)
norm(sl - sl_ref) = 0.0
(tsimd, tavx) = (1.904e-5, 1.5667e-5)
go(128) = (1.904e-5, 1.5667e-5)
(1.904e-5, 1.5667e-5)

julia> @show go(256)
norm(sl - sl_ref) = 0.0
(tsimd, tavx) = (7.349e-5, 6.4842e-5)
go(256) = (7.349e-5, 6.4842e-5)
(7.349e-5, 6.4842e-5)
```
Redefining `smooth_line_avx` like in the original non-working example (with seprange loops):
```julia
julia> @inline function smooth_line_avx(nrm1,j,i1,sl,rl,ih2,denom)
           @avx for i=i1:2:nrm1
                   sl[i,j]=denom*(rl[i,j]+ih2*(sl[i,j-1]+sl[i-1,j]+sl[i+1,j]+sl[i,j+1]))
           end
       end
smooth_line_avx (generic function with 1 method)

julia> @show go(128)
norm(sl - sl_ref) = 0.0
(tsimd, tavx) = (1.8695e-5, 1.6289e-5)
go(128) = (1.8695e-5, 1.6289e-5)
(1.8695e-5, 1.6289e-5)

julia> @show go(256)
norm(sl - sl_ref) = 0.0
(tsimd, tavx) = (7.1003e-5, 6.605e-5)
go(256) = (7.1003e-5, 6.605e-5)
(7.1003e-5, 6.605e-5)
```

**Comment by chriselrod** [comment]
As of the commit that follows this comment (should push that commit within the next hour), fixes #189 :
```julia
julia> broutine_z_avx!(copy(st), Val(:Z), 19) ≈ broutine_z!(copy(st), Val(:Z), 19)
true

julia> @benchmark broutine_z_avx!(st, Val(:Z), 19) setup=(st=rand(ComplexF64, 1 << $n))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     140.593 μs (0.00% GC)
  median time:      216.166 μs (0.00% GC)
  mean time:        200.251 μs (0.00% GC)
  maximum time:     244.483 μs (0.00% GC)
  --------------
  samples:          3127
  evals/sample:     1

julia> @benchmark broutine_z!(st, Val(:Z), 19) setup=(st=rand(ComplexF64, 1 << $n))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     141.361 μs (0.00% GC)
  median time:      198.926 μs (0.00% GC)
  mean time:        200.677 μs (0.00% GC)
  maximum time:     246.956 μs (0.00% GC)
  --------------
  samples:          3122
  evals/sample:     1

julia> broutine_z_expanded!(copy(st), Val(:Z), 19) ≈ broutine_z!(copy(st), Val(:Z), 19)
true

julia> @benchmark broutine_z_expanded!(st, Val(:Z), 19) setup=(st=rand(ComplexF64, 1 << $n))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     139.300 μs (0.00% GC)
  median time:      200.017 μs (0.00% GC)
  mean time:        199.695 μs (0.00% GC)
  maximum time:     249.390 μs (0.00% GC)
  --------------
  samples:          2947
  evals/sample:     1
```

**Comment by chriselrod** [comment]
The bump in compat to require VectorizationBase 0.19.6
fixes #64 
fixes #206

**Comment by chriselrod** [comment]
All tests pass! I'll merge soon.

**Comment by chriselrod** [comment]
Assuming all tests pass again, I'll merge and issue a new release.

Then PRs for Gaius.jl, Octavian.jl, and BLASBenchmarksCPU.jl.

**Pull request merged**
