### PR TITLE
Replace 0x0000000000000000 with zero(UInt) for 32-bit systems

### PR DESCRIPTION
**Pull request by brenhinkeller**
May avoid problems on 32-bit systems (if anyone is using Julia on those anyways?)

### CODE REVIEW

**Review by chriselrod — APPROVED** [review]
I won't auto-merge, as Macs have been failing on master.
So I'll wait for (other) tests to pass and then merge manually.

**Comment by chriselrod** [comment]
Huh, actually, there is a red x on the last commit into master, yet I couldn't find the test that actually failed.

**Comment by brenhinkeller** [comment]
Oh I think the red x might actually just be from the codecov?

**Comment by brenhinkeller** [comment]
Yeah I think it's just this -0.4% from statistical noise

Screen Shot 2022-04-08 at 11 38 54 PM

I copy-pasted some stuff into my codecov.yml that seems to stop that from happening (e.g. https://github.com/brenhinkeller/NaNStatistics.jl/blob/main/codecov.yml -- though not sure if it's the "threshold" or "target" value or both that actually does the trick)

**Comment by chriselrod** [comment]
Looks like all nightly tests have passed.

**Comment by brenhinkeller** [comment]
Tests look good on nightly on my mac and 32-bit tests are passing on NaNStatistics so I'll call it success! Nightly may just be a bit flakey lately

**Pull request merged**
